language: r

sudo: required

before_install:
  - sudo pip install music21
  - sudo pip install h5py

addons:
  apt:
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libproj-dev
      - valgrind
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - tesseract-ocr-por
      - tesseract-ocr
      - libudunits2-dev
      - lilypond

cache: packages

before_script:
  - pip2.7 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

